apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: if3d8z0ee-python
  janus-idp.io/tekton: if3d8z0ee-python
  backstage.io/kubernetes-id: if3d8z0ee-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: if3d8z0ee-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
